### ISSUE TITLE
[BUG] install lacks libapache2-mod-php7.0

### ISSUE THREAD

**Issue by ulvida** [geerlingguy/ansible-role-phpmyadmin#18]
On a debian stretch on a proxmox LXC, the installation is not completed: the `http://<server>/phpmyadmin` page shows the php code, not the phpmyadmin login. 

This is due to the lack of the package `libapache2-mod-php7.0` which is needed to have the php interpreter in apache. 

On another hand, on debian buster, the php role fails when it tries to install php7.0 when default in buster is 7.3. 

By the way, thanks a lot for all your good roles in ansile galaxy.

**Comment by geerlingguy** [comment]
@ulvida - This role assumes you've already set up apache with mod-php, or some other apache-php integration.

See the test playbook here, for example: https://github.com/geerlingguy/ansible-role-phpmyadmin/blob/master/molecule/default/playbook.yml

Also, for different PHP versions I usually use the `geerlingguy.php-versions` role which allows me to more easily specify a version like 7.1, 7.2, 7.3, etc. instead of having to override a bunch of default variables.
