### ISSUE TITLE
Support for PHP7 and nginx?

### ISSUE THREAD

**Issue by itsazzad** [geerlingguy/ansible-role-phpmyadmin#5]
Will it support the system with nginx, MariaDB, PHP7? Or anyway to make so?

**Comment by geerlingguy** [comment]
I've been using that setup for many of my PHP applications/sites for the past month and everything works great. However, as far as _phpmyadmin itself_ is concerned, I have no idea (since I don't use it much anymore).

I usually use Adminer instead (see https://github.com/geerlingguy/ansible-role-adminer).

It looks like PHPMyAdmin says it _is_ compatible, at the latest version: https://www.phpmyadmin.net/downloads/
